# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'ios14.6.TodoListRealmCoreData' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for Lesson14
  pod 'Realm', :modular_headers => true
  pod 'RealmSwift', :modular_headers => true
#  pod 'DTTableViewManager'
#  pod 'SnapKit', '~> 5.0.0'
#  pod 'RxSwift', '~> 5'
#  pod 'RxCocoa', '~> 5'

end
